config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :tweets
  root 'tweets#index'


end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = Tweet.all.paginate(page: params[:page], per_page: 4)
  end


def create
  @tweet = Tweet.create(tweet_params)
  redirect_to root_path 
end

def update
  @tweet = Tweet.create(tweet_params)
  redirect_to root_path 
end

def show
  @tweet = Tweet.find(params[:id])
end

def new
  @tweet = Tweet.new
end

def edit
  @tweet = Tweet.find(params[:id])
end

def destroy
   @tweet = Tweet.find(params[:id])
      @tweet.destroy
    redirect_to root_path
end

private
  def tweet_params
    params.require(:tweet).permit(:message)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweet_helper.rb
module TweetHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Starter Template for Bootstrap</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Project name", "#", :class => "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
         
        <li class="page-scroll"><%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
        </li>

       <% else %>    
       <li class="page-scroll">
        <a href="/users/sign_in">Sign in</a>
      </li>
      <li class="page-scroll">
        <a href="/users/sign_up">Sign up</a>
      </li>
      <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable" do %>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/tweets/_tweetsform.erb
  <%= form_for @tweet do |f| %>

    <%= f.text_field :message %>
   
      <%= f.submit  'Add tweet'%>
  
  <% end %>

app/views/tweets/edit.html.erb
  <%= render "tweetsform" %>


  <a href="/"><button > back to tweets</button></a>

app/views/tweets/index.html.erb
<h1>hello world</h1>

<%= will_paginate @things %>


<%  @tweets.each do |show| %>
<p><%= show.message %>
  <%= link_to 'Destroy', tweet_path(show.id), method: :delete, data: { confirm: 'Are you sure?' } %>
  <%= link_to 'Edit', edit_tweet_path(show.id) %></p>

<% end %>
<%= will_paginate @things %>
<br>

<a href="tweets/new"><button > add a tweet</button></a>

app/views/tweets/new.html.erb
<%= render "tweetsform" %>
  <a href="/"><button > back to tweets</button></a>